# Generated by Django 5.1.7 on 2025-03-25 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=30)),
                ('turno', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantidade_estoque', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('validade', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
