# Generated by Django 5.1.7 on 2025-03-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('Fucionário', 'F'), ('Gerente', 'G')], default='Funcionário', max_length=20),
        ),
    ]
