# Generated by Django 5.1.7 on 2025-03-25 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_funcionario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantidade_estoque', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('validade', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('Fucionário', 'Caixa'), ('Gerente', 'Gerente')], default='Funcionário', max_length=20),
        ),
    ]
