# Generated by Django 5.1.7 on 2025-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_produto_delete_produtos_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
