# Generated by Django 5.1.7 on 2025-03-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_cadastro_cliente_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sistema.fornecedor'),
        ),
    ]
